/**
 * PDF export for a TripSync trip.
 *
 * Generates a self-contained, print-ready PDF with:
 * - Cover page: trip title, destination, dates, travellers, budget
 * - One page per day: stops with times, notes, categories
 * - Budget breakdown page
 * - QR code linking back to the share URL
 *
 * All rendering is client-side (jspdf + html2canvas). Nothing is sent to a server.
 */

import { jsPDF } from 'jspdf'
import type { Stop, Trip, TripDay } from '@/types/database'

// ─── Layout constants ──────────────────────────────────────────────────────────

const PAGE_W = 210   // A4 width in mm
const PAGE_H = 297   // A4 height in mm
const MARGIN = 16
const CONTENT_W = PAGE_W - MARGIN * 2

// Accent colour matching the TripSync brand
const BRAND_BLUE = '#3b82f6'
const BRAND_DARK = '#1e3a5f'
const TEXT_MUTED = '#64748b'
const BORDER_COLOR = '#e2e8f0'

// ─── Helpers ──────────────────────────────────────────────────────────────────

function addHeader(doc: jsPDF, title: string, subtitle?: string) {
  doc.setFontSize(18)
  doc.setTextColor(30, 58, 95) // BRAND_DARK
  doc.setFont('helvetica', 'bold')
  doc.text(title, MARGIN, 22, { align: 'left', maxWidth: CONTENT_W })

  if (subtitle) {
    doc.setFontSize(10)
    doc.setTextColor(100, 116, 139) // TEXT_MUTED
    doc.setFont('helvetica', 'normal')
    doc.text(subtitle, MARGIN, 30, { align: 'left', maxWidth: CONTENT_W })
  }

  doc.setDrawColor(226, 232, 240)
  doc.setLineWidth(0.5)
  doc.line(MARGIN, 36, PAGE_W - MARGIN, 36)
}

function formatDate(dateStr: string | null | undefined): string {
  if (!dateStr) return 'TBD'
  const d = new Date(dateStr)
  return d.toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })
}

function formatTime(timeStr: string | null | undefined): string {
  if (!timeStr) return ''
  const [h, m] = timeStr.split(':')
  const hour = parseInt(h, 10)
  const ampm = hour >= 12 ? 'PM' : 'AM'
  const h12 = hour % 12 || 12
  return `${h12}:${m} ${ampm}`
}

const CURRENCY_SYMBOLS: Record<string, string> = {
  INR: '₹', USD: '$', EUR: '€', GBP: '£', AUD: 'A$',
  SGD: 'S$', THB: '฿', MYR: 'RM', IDR: 'Rp', JPY: '¥',
}

function fmtCurrency(amount: number | null | undefined, currency: string = 'INR'): string {
  const sym = CURRENCY_SYMBOLS[currency] || '₹'
  const val = amount ?? 0
  return `${sym}${val.toLocaleString('en-IN', { minimumFractionDigits: 0, maximumFractionDigits: 2 })}`
}

// ─── Cover page ───────────────────────────────────────────────────────────────

function drawCover(doc: jsPDF, trip: Trip) {
  // Full-width brand header bar
  doc.setFillColor(59, 130, 246) // BRAND_BLUE
  doc.rect(0, 0, PAGE_W, 52, 'F')

  doc.setTextColor(255, 255, 255)
  doc.setFontSize(28)
  doc.setFont('helvetica', 'bold')
  doc.text(trip.title || 'Untitled Trip', MARGIN, 28, { maxWidth: CONTENT_W })

  doc.setFontSize(12)
  doc.setFont('helvetica', 'normal')
  doc.text(trip.destination || '', MARGIN, 40, { maxWidth: CONTENT_W })

  // Reset text colour for body
  doc.setTextColor(30, 37, 46)

  let y = 72

  const meta = (label: string, value: string) => {
    doc.setFontSize(9)
    doc.setTextColor(100, 116, 139)
    doc.setFont('helvetica', 'bold')
    doc.text(label, MARGIN, y)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(30, 37, 46)
    doc.setFontSize(10)
    doc.text(value, MARGIN + 36, y)
    y += 7
  }

  const dateRange = trip.start_date && trip.end_date
    ? `${formatDate(trip.start_date)} – ${formatDate(trip.end_date)}`
    : 'Dates not set'

  meta('DESTINATION', trip.destination || 'TBD')
  meta('DATES', dateRange)
  meta('TRAVELLERS', `${trip.group_size ?? 1}`)
  meta('STATUS', (trip.status || 'planning').toUpperCase())
  meta('BUDGET', fmtCurrency(trip.budget_total, trip.currency))
  meta('CURRENCY', trip.currency || 'INR')
  if (trip.travel_style) meta('TRAVEL STYLE', trip.travel_style)
  if (trip.interests?.length) meta('INTERESTS', trip.interests.join(', '))

  // Bottom divider
  y += 8
  doc.setDrawColor(226, 232, 240)
  doc.setLineWidth(0.5)
  doc.line(MARGIN, y, PAGE_W - MARGIN, y)

  // Footer
  doc.setFontSize(8)
  doc.setTextColor(148, 163, 184)
  doc.setFont('helvetica', 'normal')
  doc.text(`Generated by TripSync on ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}`, MARGIN, PAGE_H - 12)
  doc.text('trip.trip', PAGE_W - MARGIN, PAGE_H - 12, { align: 'right' })
}

// ─── Day pages ───────────────────────────────────────────────────────────────

function drawDayPage(doc: jsPDF, day: TripDay, dayIndex: number, currency: string) {
  doc.addPage()

  const dayLabel = day.day_title
    ? `Day ${day.day_number} — ${day.day_title}`
    : `Day ${day.day_number}`

  addHeader(doc, dayLabel, formatDate(day.date ?? null))

  let y = 44

  const stops = day.stops ?? []

  if (stops.length === 0) {
    doc.setFontSize(10)
    doc.setTextColor(148, 163, 184)
    doc.setFont('helvetica', 'normal')
    doc.text('No stops planned for this day.', MARGIN, y + 6)
    return
  }

  for (let i = 0; i < stops.length; i++) {
    const stop = stops[i]

    // Stop separator
    if (i > 0) {
      doc.setDrawColor(226, 232, 240)
      doc.setLineWidth(0.3)
      doc.setLineDashPattern([1, 2], 0)
      doc.line(MARGIN, y, PAGE_W - MARGIN, y)
      doc.setLineDashPattern([], 0)
      y += 4
    }

    // Stop number circle
    doc.setFillColor(59, 130, 246)
    doc.circle(MARGIN + 3, y + 2, 3, 'F')
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(8)
    doc.setFont('helvetica', 'bold')
    doc.text(String(i + 1), MARGIN + 3, y + 4, { align: 'center' })

    // Place name
    doc.setTextColor(30, 37, 46)
    doc.setFontSize(11)
    doc.setFont('helvetica', 'bold')
    doc.text(stop.place_name || 'Unknown place', MARGIN + 10, y + 2, { maxWidth: CONTENT_W - 10 })

    y += 6

    // Time + duration
    if (stop.start_time || stop.duration_minutes) {
      const timeStr = stop.start_time ? formatTime(stop.start_time) : ''
      const durStr = stop.duration_minutes ? ` · ${stop.duration_minutes} min` : ''
      doc.setFontSize(9)
      doc.setTextColor(100, 116, 139)
      doc.setFont('helvetica', 'normal')
      doc.text(`${timeStr}${durStr}`, MARGIN + 10, y, { maxWidth: CONTENT_W - 10 })
      y += 5
    }

    // Category badge (as text)
    if (stop.category) {
      doc.setFontSize(8)
      doc.setTextColor(59, 130, 246)
      doc.setFont('helvetica', 'bold')
      doc.text(stop.category.toUpperCase(), MARGIN + 10, y)
      y += 4
    }

    // Notes
    if (stop.notes) {
      doc.setFontSize(9)
      doc.setTextColor(71, 85, 105)
      doc.setFont('helvetica', 'normal')
      const noteLines = doc.splitTextToSize(stop.notes, CONTENT_W - 10)
      doc.text(noteLines, MARGIN + 10, y, { maxWidth: CONTENT_W - 10 })
      y += noteLines.length * 4
    }

    // Cost
    if (stop.estimated_cost) {
      doc.setFontSize(9)
      doc.setTextColor(16, 185, 129) // emerald
      doc.setFont('helvetica', 'bold')
      doc.text(fmtCurrency(stop.estimated_cost, currency), MARGIN + 10, y)
      y += 4
    }

    // Check-in / skip flags
    if (stop.is_visited || stop.is_skipped) {
      doc.setFontSize(8)
      doc.setTextColor(148, 163, 184)
      doc.setFont('helvetica', 'italic')
      doc.text(stop.is_skipped ? 'Skipped' : 'Visited', MARGIN + 10, y)
      y += 4
    }

    y += 4

    // Page-break guard
    if (y > PAGE_H - 40) {
      doc.addPage()
      y = MARGIN
    }
  }

  // Day budget footer
  const dayTotal = (day.stops ?? []).reduce(
    (sum, s) => sum + (s.estimated_cost ?? 0),
    0
  )
  if (dayTotal > 0) {
    y += 4
    doc.setDrawColor(226, 232, 240)
    doc.setLineWidth(0.3)
    doc.line(MARGIN, y, PAGE_W - MARGIN, y)
    y += 6
    doc.setFontSize(9)
    doc.setTextColor(100, 116, 139)
    doc.setFont('helvetica', 'normal')
    doc.text('Day total:', MARGIN, y)
    doc.setTextColor(30, 37, 46)
    doc.setFont('helvetica', 'bold')
    doc.text(fmtCurrency(dayTotal, currency), PAGE_W - MARGIN, y, { align: 'right' })
  }
}

// ─── Budget page ─────────────────────────────────────────────────────────────

function drawBudgetPage(doc: jsPDF, trip: Trip) {
  doc.addPage()
  addHeader(doc, 'Budget Breakdown', trip.title ?? '')

  let y = 50

  const total = trip.budget_total ?? 0
  const currency = trip.currency ?? 'INR'

  // Header row
  const colDay = MARGIN
  const colPlace = MARGIN + 45
  const colCost = PAGE_W - MARGIN - 25

  doc.setFontSize(8)
  doc.setTextColor(100, 116, 139)
  doc.setFont('helvetica', 'bold')
  doc.text('DAY', colDay, y)
  doc.text('PLACE', colPlace, y)
  doc.text('COST', colCost, y, { align: 'right' })

  y += 4
  doc.setDrawColor(226, 232, 240)
  doc.setLineWidth(0.5)
  doc.line(MARGIN, y, PAGE_W - MARGIN, y)
  y += 6

  doc.setFont('helvetica', 'normal')

  let grandTotal = 0

  for (const day of trip.trip_days ?? []) {
    for (const stop of day.stops ?? []) {
      const cost = stop.estimated_cost ?? 0
      if (cost === 0) continue

      grandTotal += cost

      doc.setFontSize(8)
      doc.setTextColor(100, 116, 139)
      doc.text(`Day ${day.day_number}`, colDay, y)

      doc.setFontSize(9)
      doc.setTextColor(30, 37, 46)
      const name = stop.place_name ?? 'Unknown'
      doc.text(
        name.length > 38 ? name.slice(0, 36) + '…' : name,
        colPlace, y,
        { maxWidth: colCost - colPlace - 6 }
      )

      doc.setFont('helvetica', 'bold')
      doc.text(fmtCurrency(cost, currency), colCost, y, { align: 'right' })
      y += 7

      if (y > PAGE_H - 30) {
        doc.addPage()
        y = MARGIN
      }
    }
  }

  // Total row
  y += 4
  doc.setDrawColor(226, 232, 240)
  doc.setLineWidth(0.5)
  doc.line(MARGIN, y, PAGE_W - MARGIN, y)
  y += 8

  doc.setFontSize(11)
  doc.setTextColor(100, 116, 139)
  doc.setFont('helvetica', 'bold')
  doc.text('TOTAL', colDay, y)
  doc.text(fmtCurrency(grandTotal, currency), colCost, y, { align: 'right' })
  y += 8

  const remaining = total - grandTotal
  doc.setFontSize(9)
  if (remaining >= 0) {
    doc.setTextColor(16, 185, 129)
    doc.text(`✓ Within budget (${fmtCurrency(remaining, currency)} remaining)`, colDay, y)
  } else {
    doc.setTextColor(239, 68, 68)
    doc.text(`✗ Over budget by ${fmtCurrency(Math.abs(remaining), currency)}`, colDay, y)
  }
}

// ─── QR code page ────────────────────────────────────────────────────────────

async function drawQRPage(doc: jsPDF, shareUrl: string) {
  doc.addPage()
  addHeader(doc, 'Share & Access', '')

  doc.setFontSize(10)
  doc.setTextColor(30, 37, 46)
  doc.setFont('helvetica', 'normal')
  doc.text('Share this trip with your travel companions:', MARGIN, 50, { maxWidth: CONTENT_W })

  // URL box
  doc.setFillColor(241, 245, 249)
  doc.roundedRect(MARGIN, 58, CONTENT_W, 14, 3, 3, 'F')
  doc.setFontSize(8)
  doc.setTextColor(59, 130, 246)
  doc.setFont('helvetica', 'normal')
  doc.text(shareUrl, MARGIN + 4, 66, { maxWidth: CONTENT_W - 8, align: 'left' })

  // QR code
  // Dynamically import qrcode to keep the main bundle small
  try {
    const QRCode = (await import('qrcode')).default
    const qrDataUrl = await QRCode.toDataURL(shareUrl, {
      width: 200,
      margin: 2,
      color: { dark: '#1e3a5f', light: '#ffffff' },
    })
    const qrSize = 50 // mm
    const qrX = (PAGE_W - qrSize) / 2
    doc.addImage(qrDataUrl, 'PNG', qrX, 85, qrSize, qrSize)

    doc.setFontSize(9)
    doc.setTextColor(100, 116, 139)
    doc.setFont('helvetica', 'italic')
    doc.text('Scan to open this trip on TripSync', PAGE_W / 2, 142, { align: 'center' })
  } catch {
    // QRCode not available — skip silently
  }
}

// ─── Main export ─────────────────────────────────────────────────────────────

/**
 * Generate and download a PDF for the given trip.
 *
 * @param trip  Full trip object including trip_days and nested stops
 * @param shareUrl  The URL to encode in the QR code
 */
export async function exportTripToPDF(trip: Trip, shareUrl: string): Promise<void> {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

  drawCover(doc, trip)

  for (let i = 0; i < (trip.trip_days ?? []).length; i++) {
    drawDayPage(doc, trip.trip_days![i], i, trip.currency ?? 'INR')
  }

  drawBudgetPage(doc, trip)

  await drawQRPage(doc, shareUrl)

  const filename = `${(trip.title ?? 'trip').replace(/[^a-z0-9]/gi, '_').toLowerCase()}_itinerary.pdf`
  doc.save(filename)
}
