import { NextRequest, NextResponse } from 'next/server'
import { getCurrentUserId } from '@/lib/auth/server'

// Model IDs are pinned here (and overridable via env) because providers retire
// them without warning — the previous two, groq/llama-3.1-8b-instant and
// gemini-2.0-flash, were both decommissioned and returned 404 model_not_found,
// which made every generation fail.
const GROQ_MODEL = process.env.GROQ_MODEL ?? 'openai/gpt-oss-120b'
const GEMINI_MODEL = process.env.GEMINI_MODEL ?? 'gemini-3.6-flash'

interface TripParams {
  destination: string
  startDate: string
  endDate: string
  budgetTotal: number
  currency: string
  travelStyle: string
  interests: string[]
  groupSize: number
}

interface Stop {
  position: number
  place_name: string
  category: string
  address: string
  start_time: string
  duration_minutes: number
  estimated_cost: number
  travel_time_from_prev: number
  travel_mode: string
  opening_hours: string
  notes: string
}

interface Day {
  day_number: number
  date: string
  day_title: string
  stops: Stop[]
}

interface GeneratedItinerary {
  trip_title: string
  days: Day[]
  total_estimated_cost: number
  trip_summary: string
}

function buildPrompt(params: TripParams): string {
  const startDate = new Date(params.startDate)
  const endDate = new Date(params.endDate)
  const numDays = Math.ceil((endDate.getTime() - startDate.getTime()) / (1000 * 60 * 60 * 24)) + 1
  const budgetPerDay = Math.round(params.budgetTotal / numDays)

  return `You are TripSync's constraint-aware travel planning engine.

Generate a detailed day-by-day itinerary for the following trip:
- Destination: ${params.destination}
- Duration: ${params.startDate} to ${params.endDate} (${numDays} days)
- Budget: ${params.currency} ${params.budgetTotal} total (approx ${params.currency} ${budgetPerDay}/day)
- Travel Style: ${params.travelStyle}
- Interests: ${params.interests.join(', ')}
- Group Size: ${params.groupSize}

HARD CONSTRAINTS you must follow:
1. Each stop must have a realistic time slot. No teleporting — account for travel time between stops.
2. Restaurants must appear at meal times (breakfast 7-9am, lunch 12-2pm, dinner 7-9pm).
3. Attractions must be open during assigned time (museums typically close by 6pm, nightlife starts 9pm+).
4. First and last day: account for check-in/check-out. First stop Day 1 should be no earlier than 2pm if arriving by flight.
5. Total estimated cost across all stops must stay within budget.
6. Maximum 5-6 stops per day (tourists get tired).
7. Group stops geographically — minimize backtracking within a day.

Respond ONLY with a valid JSON object. No markdown, no explanation. Format:
{
  "trip_title": "string",
  "days": [
    {
      "day_number": 1,
      "date": "YYYY-MM-DD",
      "day_title": "string",
      "stops": [
        {
          "position": 1,
          "place_name": "string",
          "category": "attraction|food|hotel|activity|transport|shopping",
          "address": "string",
          "start_time": "HH:MM",
          "duration_minutes": 90,
          "estimated_cost": 500,
          "travel_time_from_prev": 20,
          "travel_mode": "walk|auto|transit|drive",
          "opening_hours": "9:00 AM - 6:00 PM",
          "notes": "string — useful tip for this place"
        }
      ]
    }
  ],
  "total_estimated_cost": 12000,
  "trip_summary": "2-3 sentence overview of this trip"
}`
}

async function generateWithGemini(prompt: string): Promise<GeneratedItinerary | null> {
  const apiKey = process.env.GEMINI_API_KEY
  
  if (!apiKey) {
    console.error('Gemini API key not configured. Please set GEMINI_API_KEY in .env.local')
    return null
  }

  try {
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent?key=${apiKey}`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [{
            parts: [{
              text: prompt
            }]
          }],
          generationConfig: {
            temperature: 0.7,
            topK: 40,
            topP: 0.95,
            maxOutputTokens: 16384,
            responseMimeType: 'application/json',
          }
        })
      }
    )

    if (!response.ok) {
      const errorText = await response.text()
      console.error('Gemini API error:', response.status, errorText)
      return null
    }

    const data = await response.json()
    const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text

    if (!generatedText) {
      console.error('No text generated by Gemini')
      return null
    }

    // Parse JSON from response (remove markdown code blocks if present)
    let jsonStr = generatedText.trim()
    if (jsonStr.startsWith('```json')) {
      jsonStr = jsonStr.slice(7)
    } else if (jsonStr.startsWith('```')) {
      jsonStr = jsonStr.slice(3)
    }
    if (jsonStr.endsWith('```')) {
      jsonStr = jsonStr.slice(0, -3)
    }

    const itinerary = JSON.parse(jsonStr.trim()) as GeneratedItinerary
    return itinerary
  } catch (error) {
    console.error('Gemini generation error:', error)
    return null
  }
}

async function generateWithGroq(prompt: string): Promise<GeneratedItinerary | null> {
  const apiKey = process.env.GROQ_API_KEY
  
  if (!apiKey) {
    console.error('Groq API key not configured')
    return null
  }

  try {
    const response = await fetch(
      'https://api.groq.com/openai/v1/chat/completions',
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${apiKey}`
        },
        body: JSON.stringify({
          model: GROQ_MODEL,
          messages: [{
            role: 'user',
            content: prompt
          }],
          temperature: 0.7,
          max_tokens: 8192,
          response_format: { type: 'json_object' }
        })
      }
    )

    if (!response.ok) {
      const errorText = await response.text()
      console.error('Groq API error:', response.status, errorText)
      return null
    }

    const data = await response.json()
    const generatedText = data.choices?.[0]?.message?.content

    if (!generatedText) {
      console.error('No text generated by Groq')
      return null
    }

    // Parse JSON from response
    let jsonStr = generatedText.trim()
    console.log('Groq raw response preview:', jsonStr.substring(0, 200))
    
    if (jsonStr.startsWith('```json')) {
      jsonStr = jsonStr.slice(7)
    } else if (jsonStr.startsWith('```')) {
      jsonStr = jsonStr.slice(3)
    }
    if (jsonStr.endsWith('```')) {
      jsonStr = jsonStr.slice(0, -3)
    }

    try {
      const itinerary = JSON.parse(jsonStr.trim()) as GeneratedItinerary
      return itinerary
    } catch (parseError) {
      console.error('JSON parse error:', parseError)
      console.error('JSON string that failed:', jsonStr.substring(0, 500))
      return null
    }
  } catch (error) {
    console.error('Groq generation error:', error)
    return null
  }
}

export async function POST(request: NextRequest) {
  try {
    const userId = await getCurrentUserId()

    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const body = await request.json()
    const params: TripParams = {
      destination: body.destination,
      startDate: body.startDate,
      endDate: body.endDate,
      budgetTotal: parseFloat(body.budgetTotal) || 0,
      currency: body.currency || 'INR',
      travelStyle: body.travelStyle || 'solo',
      interests: body.interests || [],
      groupSize: parseInt(body.groupSize) || 1
    }

    // Validate required fields
    if (!params.destination || !params.startDate || !params.endDate) {
      return NextResponse.json(
        { error: 'Missing required fields: destination, startDate, endDate' },
        { status: 400 }
      )
    }

    // Build the prompt
    const prompt = buildPrompt(params)

    // Try Groq first, then fallback to Gemini
    console.log('Starting itinerary generation...')
    console.log('Prompt length:', prompt.length)
    
    let itinerary = await generateWithGroq(prompt)
    
    if (!itinerary) {
      console.log('Groq failed, trying Gemini...')
      itinerary = await generateWithGemini(prompt)
    }

    if (!itinerary) {
      console.log('Both AI providers failed')
      return NextResponse.json(
        { error: 'Failed to generate itinerary. Please try again. Check the server logs for details.' },
        { status: 500 }
      )
    }

    console.log('Itinerary generated successfully!')

    return NextResponse.json({
      success: true,
      itinerary
    })

  } catch (error) {
    console.error('Generate itinerary error:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}
